name: master-deploy

on:
  push:
    branches:
      - master

concurrency: master-deploy

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3.8.1
        with:
          node-version: 16
      - run: yarn install
      - run: yarn test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    environment: production
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Publish
        uses: cloudflare/wrangler-action@v3.4.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
